# Generated by Django 3.0 on 2021-05-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210515_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='product/products'),
        ),
    ]
