# Generated by Django 3.0 on 2021-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210515_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=19),
        ),
    ]
