# Generated by Django 3.0 on 2021-05-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210507_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
    ]
