# Generated by Django 3.0 on 2021-05-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isLike',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
