# Generated by Django 3.0 on 2021-05-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_islike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isLike',
        ),
    ]
