# Generated by Django 3.0 on 2021-06-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210602_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='goal',
        ),
    ]
