# Generated by Django 3.0 on 2021-05-31 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messenger', '0002_auto_20210601_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='person',
        ),
        migrations.RemoveField(
            model_name='message',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
