# Generated by Django 3.0 on 2021-05-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0003_auto_20210601_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='slug',
            field=models.SlugField(max_length=2000),
        ),
    ]
