# Generated by Django 3.0 on 2021-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20210528_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
